server:
  port: 8898
  servlet:
    encoding:
      force-response: true



spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studyhere
    username: root
    password: 1234


  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database : mysql
    hibernate.ddl-auto : update
    default_batch_fetch_size: 1000
    generate-ddl : false
    properties.hibernate.format_sql : true
    properties.hibernate.enable_lazy_load_no_trans : true

jwt:
  token:
    secret: payhere.hello.world

app:
  host: ec2-52-79-237-83.ap-northeast-2.compute.amazonaws.com